"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Gui.py']
DATA_FILES = ['myfile.json', 'myfile.txt']
OPTIONS = {'argv_emulation': True,'includes':['glob', 'os']}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
